# /etc/greetd/config.toml
[terminal]
vt = 1

# Styling options for tuigreet
[default_session]
command = "tuigreet --time --time-format '%Y-%m-%d %H:%M:%S' --greeting 'Welcome to Niri' --asterisks --asterisks-char '*' --window-padding 2 --container-padding 2 --prompt-padding 1 --remember --remember-session --cmd /home/xxx/.local/bin/niri-session"
